name: Workflow - Enable

on:
  workflow_dispatch:
    inputs:
      workflow_file:
        default: deploy_environment__cloud_run.yml
        required: true
        description: The workflow file

jobs:
  enable_workflow:
    name: Enable Workflow

    runs-on: ubuntu-latest

    steps:
      - name: Enable workflow
        uses: actions/github-script@v3
        env:
          workflow_file: ${{ github.event.inputs.workflow_file }}
        with:
          script: |
            class WorkflowEnablement {
              constructor(workflowFile) {
                this.workflow = workflowFile;
              }

              enable() {
                return github.request(
                  'PUT /repos/{owner}/{repo}/actions/workflows/{workflow_id}/enable',
                  {
                    ...context.repo,
                    workflow_id: this.workflow
                  }
                );
              }

              disable() {
                  return github.request(
                  'PUT /repos/{owner}/{repo}/actions/workflows/{workflow_id}/disable',
                  {
                    ...context.repo,
                    workflow_id: this.workflow
                  }
                );
              }
            }
            
            const workflow = new WorkflowEnablement(process.env.workflow_file);
            await workflow.enable();